/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppointmentsRouteImport } from './routes/appointments'
import { Route as FinanceRouteImport } from './routes/finance'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PatientsRouteImport } from './routes/patients'
import { Route as PaymentsRouteImport } from './routes/payments'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as CheckInFollowupRouteImport } from './routes/check-in.followup'
import { Route as CheckInNewRouteImport } from './routes/check-in.new'
import { Route as PatientsIndexRouteImport } from './routes/patients.index'
import { Route as PatientsPatientIdRouteImport } from './routes/patients.$patientId'
import { Route as PatientsNewRouteImport } from './routes/patients.new'
import { Route as PaymentsIndexRouteImport } from './routes/payments.index'
import { Route as PaymentsNewRouteImport } from './routes/payments.new'
import { Route as PatientsPatientIdIndexRouteImport } from './routes/patients.$patientId.index'
import { Route as QueueQueueIdBillRouteImport } from './routes/queue.$queueId.bill'
import { Route as PatientsPatientIdVisitsNewRouteImport } from './routes/patients.$patientId.visits.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppointmentsRoute = AppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceRoute = FinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientsRoute = PatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsRoute = PaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckInFollowupRoute = CheckInFollowupRouteImport.update({
  id: '/check-in/followup',
  path: '/check-in/followup',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckInNewRoute = CheckInNewRouteImport.update({
  id: '/check-in/new',
  path: '/check-in/new',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientsIndexRoute = PatientsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PatientsRoute,
} as any)
const PatientsPatientIdRoute = PatientsPatientIdRouteImport.update({
  id: '/$patientId',
  path: '/$patientId',
  getParentRoute: () => PatientsRoute,
} as any)
const PatientsNewRoute = PatientsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => PatientsRoute,
} as any)
const PaymentsIndexRoute = PaymentsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PaymentsRoute,
} as any)
const PaymentsNewRoute = PaymentsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => PaymentsRoute,
} as any)
const PatientsPatientIdIndexRoute = PatientsPatientIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PatientsPatientIdRoute,
} as any)
const QueueQueueIdBillRoute = QueueQueueIdBillRouteImport.update({
  id: '/queue/$queueId/bill',
  path: '/queue/$queueId/bill',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientsPatientIdVisitsNewRoute =
  PatientsPatientIdVisitsNewRouteImport.update({
    id: '/visits/new',
    path: '/visits/new',
    getParentRoute: () => PatientsPatientIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/appointments': typeof AppointmentsRoute
  '/finance': typeof FinanceRoute
  '/login': typeof LoginRoute
  '/patients': typeof PatientsRouteWithChildren
  '/payments': typeof PaymentsRouteWithChildren
  '/services': typeof ServicesRoute
  '/check-in/followup': typeof CheckInFollowupRoute
  '/check-in/new': typeof CheckInNewRoute
  '/patients/$patientId': typeof PatientsPatientIdRouteWithChildren
  '/patients/new': typeof PatientsNewRoute
  '/payments/new': typeof PaymentsNewRoute
  '/patients/': typeof PatientsIndexRoute
  '/payments/': typeof PaymentsIndexRoute
  '/queue/$queueId/bill': typeof QueueQueueIdBillRoute
  '/patients/$patientId/': typeof PatientsPatientIdIndexRoute
  '/patients/$patientId/visits/new': typeof PatientsPatientIdVisitsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/appointments': typeof AppointmentsRoute
  '/finance': typeof FinanceRoute
  '/login': typeof LoginRoute
  '/services': typeof ServicesRoute
  '/check-in/followup': typeof CheckInFollowupRoute
  '/check-in/new': typeof CheckInNewRoute
  '/patients/new': typeof PatientsNewRoute
  '/payments/new': typeof PaymentsNewRoute
  '/patients': typeof PatientsIndexRoute
  '/payments': typeof PaymentsIndexRoute
  '/queue/$queueId/bill': typeof QueueQueueIdBillRoute
  '/patients/$patientId': typeof PatientsPatientIdIndexRoute
  '/patients/$patientId/visits/new': typeof PatientsPatientIdVisitsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/appointments': typeof AppointmentsRoute
  '/finance': typeof FinanceRoute
  '/login': typeof LoginRoute
  '/patients': typeof PatientsRouteWithChildren
  '/payments': typeof PaymentsRouteWithChildren
  '/services': typeof ServicesRoute
  '/check-in/followup': typeof CheckInFollowupRoute
  '/check-in/new': typeof CheckInNewRoute
  '/patients/$patientId': typeof PatientsPatientIdRouteWithChildren
  '/patients/new': typeof PatientsNewRoute
  '/payments/new': typeof PaymentsNewRoute
  '/patients/': typeof PatientsIndexRoute
  '/payments/': typeof PaymentsIndexRoute
  '/queue/$queueId/bill': typeof QueueQueueIdBillRoute
  '/patients/$patientId/': typeof PatientsPatientIdIndexRoute
  '/patients/$patientId/visits/new': typeof PatientsPatientIdVisitsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/appointments'
    | '/finance'
    | '/login'
    | '/patients'
    | '/payments'
    | '/services'
    | '/check-in/followup'
    | '/check-in/new'
    | '/patients/$patientId'
    | '/patients/new'
    | '/payments/new'
    | '/patients/'
    | '/payments/'
    | '/queue/$queueId/bill'
    | '/patients/$patientId/'
    | '/patients/$patientId/visits/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/appointments'
    | '/finance'
    | '/login'
    | '/services'
    | '/check-in/followup'
    | '/check-in/new'
    | '/patients/new'
    | '/payments/new'
    | '/patients'
    | '/payments'
    | '/queue/$queueId/bill'
    | '/patients/$patientId'
    | '/patients/$patientId/visits/new'
  id:
    | '__root__'
    | '/'
    | '/appointments'
    | '/finance'
    | '/login'
    | '/patients'
    | '/payments'
    | '/services'
    | '/check-in/followup'
    | '/check-in/new'
    | '/patients/$patientId'
    | '/patients/new'
    | '/payments/new'
    | '/patients/'
    | '/payments/'
    | '/queue/$queueId/bill'
    | '/patients/$patientId/'
    | '/patients/$patientId/visits/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppointmentsRoute: typeof AppointmentsRoute
  FinanceRoute: typeof FinanceRoute
  LoginRoute: typeof LoginRoute
  PatientsRoute: typeof PatientsRouteWithChildren
  PaymentsRoute: typeof PaymentsRouteWithChildren
  ServicesRoute: typeof ServicesRoute
  CheckInFollowupRoute: typeof CheckInFollowupRoute
  CheckInNewRoute: typeof CheckInNewRoute
  QueueQueueIdBillRoute: typeof QueueQueueIdBillRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appointments': {
      id: '/appointments'
      path: '/appointments'
      fullPath: '/appointments'
      preLoaderRoute: typeof AppointmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance': {
      id: '/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof FinanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patients': {
      id: '/patients'
      path: '/patients'
      fullPath: '/patients'
      preLoaderRoute: typeof PatientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments': {
      id: '/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof PaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/check-in/followup': {
      id: '/check-in/followup'
      path: '/check-in/followup'
      fullPath: '/check-in/followup'
      preLoaderRoute: typeof CheckInFollowupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/check-in/new': {
      id: '/check-in/new'
      path: '/check-in/new'
      fullPath: '/check-in/new'
      preLoaderRoute: typeof CheckInNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patients/': {
      id: '/patients/'
      path: '/'
      fullPath: '/patients/'
      preLoaderRoute: typeof PatientsIndexRouteImport
      parentRoute: typeof PatientsRoute
    }
    '/patients/$patientId': {
      id: '/patients/$patientId'
      path: '/$patientId'
      fullPath: '/patients/$patientId'
      preLoaderRoute: typeof PatientsPatientIdRouteImport
      parentRoute: typeof PatientsRoute
    }
    '/patients/new': {
      id: '/patients/new'
      path: '/new'
      fullPath: '/patients/new'
      preLoaderRoute: typeof PatientsNewRouteImport
      parentRoute: typeof PatientsRoute
    }
    '/payments/': {
      id: '/payments/'
      path: '/'
      fullPath: '/payments/'
      preLoaderRoute: typeof PaymentsIndexRouteImport
      parentRoute: typeof PaymentsRoute
    }
    '/payments/new': {
      id: '/payments/new'
      path: '/new'
      fullPath: '/payments/new'
      preLoaderRoute: typeof PaymentsNewRouteImport
      parentRoute: typeof PaymentsRoute
    }
    '/patients/$patientId/': {
      id: '/patients/$patientId/'
      path: '/'
      fullPath: '/patients/$patientId/'
      preLoaderRoute: typeof PatientsPatientIdIndexRouteImport
      parentRoute: typeof PatientsPatientIdRoute
    }
    '/queue/$queueId/bill': {
      id: '/queue/$queueId/bill'
      path: '/queue/$queueId/bill'
      fullPath: '/queue/$queueId/bill'
      preLoaderRoute: typeof QueueQueueIdBillRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patients/$patientId/visits/new': {
      id: '/patients/$patientId/visits/new'
      path: '/visits/new'
      fullPath: '/patients/$patientId/visits/new'
      preLoaderRoute: typeof PatientsPatientIdVisitsNewRouteImport
      parentRoute: typeof PatientsPatientIdRoute
    }
  }
}

interface PatientsPatientIdRouteChildren {
  PatientsPatientIdIndexRoute: typeof PatientsPatientIdIndexRoute
  PatientsPatientIdVisitsNewRoute: typeof PatientsPatientIdVisitsNewRoute
}

const PatientsPatientIdRouteChildren: PatientsPatientIdRouteChildren = {
  PatientsPatientIdIndexRoute: PatientsPatientIdIndexRoute,
  PatientsPatientIdVisitsNewRoute: PatientsPatientIdVisitsNewRoute,
}

const PatientsPatientIdRouteWithChildren =
  PatientsPatientIdRoute._addFileChildren(PatientsPatientIdRouteChildren)

interface PatientsRouteChildren {
  PatientsPatientIdRoute: typeof PatientsPatientIdRouteWithChildren
  PatientsNewRoute: typeof PatientsNewRoute
  PatientsIndexRoute: typeof PatientsIndexRoute
}

const PatientsRouteChildren: PatientsRouteChildren = {
  PatientsPatientIdRoute: PatientsPatientIdRouteWithChildren,
  PatientsNewRoute: PatientsNewRoute,
  PatientsIndexRoute: PatientsIndexRoute,
}

const PatientsRouteWithChildren = PatientsRoute._addFileChildren(
  PatientsRouteChildren,
)

interface PaymentsRouteChildren {
  PaymentsNewRoute: typeof PaymentsNewRoute
  PaymentsIndexRoute: typeof PaymentsIndexRoute
}

const PaymentsRouteChildren: PaymentsRouteChildren = {
  PaymentsNewRoute: PaymentsNewRoute,
  PaymentsIndexRoute: PaymentsIndexRoute,
}

const PaymentsRouteWithChildren = PaymentsRoute._addFileChildren(
  PaymentsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppointmentsRoute: AppointmentsRoute,
  FinanceRoute: FinanceRoute,
  LoginRoute: LoginRoute,
  PatientsRoute: PatientsRouteWithChildren,
  PaymentsRoute: PaymentsRouteWithChildren,
  ServicesRoute: ServicesRoute,
  CheckInFollowupRoute: CheckInFollowupRoute,
  CheckInNewRoute: CheckInNewRoute,
  QueueQueueIdBillRoute: QueueQueueIdBillRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
